alt = "penetration-testing"

title = "👾 Penetration testing"
description = "Detecting and exploiting vulnerabilities in systems"

[ru]
title = "👾 Тестирование на проникновение"
description = "Обнаружение и эксплуатация уязвимостей в системах"