title = "🏁 Routing"
description = "Principles of protocols that regulate network packet transmission"

[ru]
title = "🏁 Маршрутизация"
description = "Принципы работы протоколов, которые регулируют передачу пакетов в сети"