name: Check code

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Compile and cache build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: engine -> engine/target

      - name: Run tests
        run: cargo test --manifest-path engine/Cargo.toml --target-dir engine/target

      - name: Check formatting
        run: cargo fmt --all --check --manifest-path engine/Cargo.toml

      - name: Run clippy
        run: cargo clippy --all --tests --all-features --manifest-path engine/Cargo.toml --target-dir engine/target -- -D warnings

      - name: Test generating `public` by running release
        run: cargo run --release --manifest-path engine/Cargo.toml --target-dir engine/target
